name: "Terraform E2E Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: "Setup KinD Cluster"
        uses: helm/kind-action@v1.8.0

      - name: "Terraform Format"
        run: terraform fmt -check

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Apply"
        run: terraform apply -auto-approve

      - name: "Verify Blue Deployment"
        run: |
          kubectl wait --for=condition=ready pod -l app=app,color=blue -n bluegreen --timeout=120s
          echo "Blue deployment is ready!"

      - name: "Verify Green Deployment"
        run: |
          kubectl wait --for=condition=ready pod -l app=app,color=green -n bluegreen --timeout=120s
          echo "Green deployment is ready!"

      - name: "Verify Service"
        run: |
          kubectl get svc app-svc -n bluegreen
          echo "Service is present!"